template_path: bridgeserver2.yaml
stack_name: bridgeserver2-prod
depedencies:
  - common/bridgeserver2-common.yaml
  - prod/bridgeserver2-db.yaml
parameters:
  AppDeployBucket: org-sagebridge-bridgeserver2-deployment-prod
  AppHealthcheckUrl: '/'
  AttachmentBucket: org-sagebridge-attachment-prod
  AwsAutoScalingMaxSize: "2"
  AwsAutoScalingMinSize: "2"
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: bridge-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgeops@sagebase.org
  BridgeEnv: prod
  BridgeDBStackName: bridgeserver2-db-prod
  BridgeHealthcodeRedisKey: !ssm /bridgeserver2-prod/BridgeHealthcodeRedisKey
  BridgeUser: heroku
  DNSHostname: bridgeserver2-prod
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.medium
  EmailUnsubscribeToken: !ssm /bridgeserver2-common/EmailUnsubscribeToken
  Env: production
  HibernateConnectionPassword: !ssm /bridgeserver2-prod/HibernateConnectionPassword
  HibernateConnectionUsername: !ssm /bridgeserver2-prod/HibernateConnectionUsername
  HibernateConnectionUsessl: 'true'
  NewRelicAppName: bridgeserver2-prod
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SynapseApiKey: !ssm /bridgeserver2-prod/SynapseApiKey
  SynapseUser: !ssm /bridgeserver2-prod/SynapseUser
  SynapseOAuthClientId: !ssm /bridgeserver2-prod/SynapseOAuthClientId
  SynapseOAuthClientSecret: !ssm /bridgeserver2-prod/SynapseOAuthClientSecret
  CrcGeoCodeApiKey: !ssm /bridgeserver2-prod/CrcGeoCodeApiKey
  CuimcTestUsername: !ssm /bridgeserver2-common/CuimcTestUsername
  CuimcTestPassword: !ssm /bridgeserver2-common/CuimcTestPassword
  CuimcProdUsername: !ssm /bridgeserver2-common/CuimcProdUsername
  CuimcProdPassword: !ssm /bridgeserver2-common/CuimcProdPassword
