template_path: bridgeserver2.yaml
stack_name: bridgeserver2-develop
depedencies:
  - common/bridgeserver2-common.yaml
  - develop/bridgeserver2-db.yaml
parameters:
  AppDeployBucket: org-sagebridge-bridgeserver2-deployment-develop
  AppHealthcheckUrl: '/'
  AttachmentBucket: org-sagebridge-attachment-develop
  AwsAutoScalingMaxSize: '1'
  AwsAutoScalingMinSize: '1'
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: bridgepf-develop-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgepf-develop@sagebase.org
  BridgeEnv: dev
  BridgeDBStackName: bridgeserver2-db-develop
  BridgeHealthcodeRedisKey: !ssm /bridgeserver2-develop/BridgeHealthcodeRedisKey
  BridgeUser: heroku
  DNSHostname: bridgeserver2-develop
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.small
  EmailUnsubscribeToken: !ssm /bridgeserver2-common/EmailUnsubscribeToken
  Env: develop
  HibernateConnectionPassword: !ssm /bridgeserver2-develop/HibernateConnectionPassword
  HibernateConnectionUsername: !ssm /bridgeserver2-develop/HibernateConnectionUsername
  HibernateConnectionUsessl: 'true'
  NewRelicAppName: bridgeserver2-develop
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SynapseApiKey: !ssm /bridgeserver2-develop/SynapseApiKey
  SynapseUser: !ssm /bridgeserver2-develop/SynapseUser
  SynapseOAuthClientId: !ssm /bridgeserver2-develop/SynapseOAuthClientId
  SynapseOAuthClientSecret: !ssm /bridgeserver2-develop/SynapseOAuthClientSecret
  CrcGeoCodeApiKey: !ssm /bridgeserver2-develop/CrcGeoCodeApiKey
  CuimcTestUsername: !ssm /bridgeserver2-common/CuimcTestUsername
  CuimcTestPassword: !ssm /bridgeserver2-common/CuimcTestPassword
  CuimcProdUsername: !ssm /bridgeserver2-common/CuimcProdUsername
  CuimcProdPassword: !ssm /bridgeserver2-common/CuimcProdPassword
