template_path: bridgeserver2.yaml
stack_name: bridgeserver2-uat
depedencies:
  - common/bridgeserver2-common.yaml
  - uat/bridgeserver2-db.yaml
parameters:
  AppDeployBucket: org-sagebridge-bridgeserver2-deployment-devstaging
  AppHealthcheckUrl: '/'
  AttachmentBucket: org-sagebridge-attachment-devstaging
  AwsAutoScalingMaxSize: '1'
  AwsAutoScalingMinSize: '1'
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: bridgepf-uat-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgepf-uat@sagebase.org
  BootstrapAdminEmail: !ssm /bridgeserver2-uat/BootstrapAdminEmail
  BootstrapAdminPassword: !ssm /bridgeserver2-uat/BootstrapAdminPassword
  BridgeEnv: uat
  BridgeDBStackName: bridgeserver2-db-uat
  BridgeHealthcodeRedisKey: !ssm /bridgeserver2-uat/BridgeHealthcodeRedisKey
  BridgeUser: heroku
  BucketSuffix: devstaging
  DNSHostname: bridgeserver2-devstaging
  DNSDomain: sagebridge.org
  EC2InstanceType: t3a.small
  EmailUnsubscribeToken: !ssm /bridgeserver2-common/EmailUnsubscribeToken
  Env: staging
  ExporterRequestSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/420786776710/Bridge-EX-Request-staging
  ExporterSynapseApiKey: !ssm /bridgeserver2-uat/ExporterSynapseApiKey
  ExporterSynapseUser: !ssm /bridgeserver2-uat/ExporterSynapseUser
  HibernateConnectionPassword: !ssm /bridgeserver2-uat/HibernateConnectionPassword
  HibernateConnectionUsername: !ssm /bridgeserver2-uat/HibernateConnectionUsername
  HibernateConnectionUsessl: 'true'
  HostPostfix: -devstaging.sagebridge.org
  NewRelicAppName: bridgeserver2-devstaging
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SesNotificationTopicArn: arn:aws:sns:us-east-1:420786776710:SNSBounces
  SynapseApiKey: !ssm /bridgeserver2-uat/SynapseApiKey
  SynapseUser: !ssm /bridgeserver2-uat/SynapseUser
  SynapseOAuthClientId: !ssm /bridgeserver2-uat/SynapseOAuthClientId
  SynapseOAuthClientSecret: !ssm /bridgeserver2-uat/SynapseOAuthClientSecret
  UddSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/420786776710/Bridge-WorkerPlatform-Request-staging
  CrcGeoCodeApiKey: !ssm /bridgeserver2-uat/CrcGeoCodeApiKey
  CuimcTestUsername: !ssm /bridgeserver2-common/CuimcTestUsername
  CuimcTestPassword: !ssm /bridgeserver2-common/CuimcTestPassword
  CuimcProdUsername: !ssm /bridgeserver2-common/CuimcProdUsername
  CuimcProdPassword: !ssm /bridgeserver2-common/CuimcProdPassword
  GbfApiKey: !ssm /bridgeserver2-common/GbfApiKey
