template_path: bridgeserver2.yaml
stack_name: bridgeserver2-uat
depedencies:
  - common/bridgeserver2-common.yaml
  - uat/bridgeserver2-db.yaml
parameters:
  AppDeployBucket: org-sagebridge-bridgeserver2-deployment-uat
  AppHealthcheckUrl: '/'
  AttachmentBucket: org-sagebridge-attachment-uat
  AwsAutoScalingMaxSize: '1'
  AwsAutoScalingMinSize: '1'
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: bridgepf-uat-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgepf-uat@sagebase.org
  BridgeEnv: uat
  BridgeDBStackName: bridgeserver2-db-uat
  BridgeHealthcodeRedisKey: !ssm /bridgeserver2-uat/BridgeHealthcodeRedisKey
  BridgeUser: heroku
  DNSHostname: bridgeserver2-uat
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.small
  EmailUnsubscribeToken: !ssm /bridgeserver2-common/EmailUnsubscribeToken
  Env: staging
  HibernateConnectionPassword: !ssm /bridgeserver2-uat/HibernateConnectionPassword
  HibernateConnectionUsername: !ssm /bridgeserver2-uat/HibernateConnectionUsername
  HibernateConnectionUsessl: 'true'
  NewRelicAppName: bridgeserver2-uat
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SynapseApiKey: !ssm /bridgeserver2-uat/SynapseApiKey
  SynapseUser: !ssm /bridgeserver2-uat/SynapseUser
  SynapseOAuthClientId: !ssm /bridgeserver2-uat/SynapseOAuthClientId
  SynapseOAuthClientSecret: !ssm /bridgeserver2-uat/SynapseOAuthClientSecret
  CrcGeoCodeApiKey: !ssm /bridgeserver2-uat/CrcGeoCodeApiKey
  CuimcTestUsername: !ssm /bridgeserver2-common/CuimcTestUsername
  CuimcTestPassword: !ssm /bridgeserver2-common/CuimcTestPassword
  CuimcProdUsername: !ssm /bridgeserver2-common/CuimcProdUsername
  CuimcProdPassword: !ssm /bridgeserver2-common/CuimcProdPassword
