template_path: bridgeserver2-antivirus.yaml
stack_name: bridgeserver2-antivirus-uat
parameters:
  AlarmEmail: bridge-testing@sagebase.org
  CodeZipS3BucketParameter: org-sagebridge-deployments-devstaging
  CodeZipS3KeyParameter: virus-scanner-lambda-20230206-af70cfc.zip
  ScanTriggerSNSTopicArn: arn:aws:sns:us-east-1:420786776710:virus-scan-trigger-devstaging
  ScanResultSNSTopicArn: arn:aws:sns:us-east-1:420786776710:virus-scan-result-devstaging
  SumoLogicHttpEndpoint: https://endpoint1.collection.us2.sumologic.com/receiver/v1/http/ZaVnC4dhaV3OQvjK3ae3NYpyYtM8IfK6joLAONkQJyLkgyNFTg7CmcjjvN5_RmkuBURGOFEsqBOiaJDo0zZZ2v6e3Km1RwUf0GPH7ksr3rVk5bLNKNcpaA==
